# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d35d1f368757261de5cbc5eed5f960aa9825effb601c8e6b54a58a2504a7b45fb39943aa811f94f3580b85b5ea349678e347341d67976b5bd80a3151a39d6f9

test:
  secret_key_base: c2919f91a30a0193b653d54d42b18dc4a21a37d68f0cf568f0e31c5671f57f28d087fbb59010a195f649003db2a8c214396cca5aceec3474e80c4d7dc6fc0f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
